/**
 * عن المشروع — the About page content, written by a specialist-writer + reviewer
 * pipeline (see docs). Rendered by views/About.tsx. Prose uses \n\n paragraphs,
 * **bold**, and "- " bullet lines.
 */
export interface AboutSection { id: string; ar_heading: string; en_heading: string; ar_body: string; en_body: string; }
export const ABOUT_SECTIONS: AboutSection[] = [
  {
    "id": "mishkat-research",
    "ar_heading": "مشروعٌ بحثيٌّ في القرآن يستفيدُ من الذكاء الاصطناعيّ",
    "en_heading": "A Qur'anic research project that draws on artificial intelligence",
    "ar_body": "«مشكاة» تجربةٌ في خدمة القرآن الكريم حاسوبيًّا: نبني «رسمًا معرفيًّا محسوبًا» فوق نصّ المصحف، مستعينين بالذكاء الاصطناعيّ ضمنَ إطارٍ منضبط، لنُبرِزَ ترابُطَ الكتاب ونظمَه — كيف تتناسبُ آياتُه، وتتشابكُ جذورُه ومعانيه في نسيجٍ واحد.\n\nشعارُنا: **«نحسبُ ونعرض».** نحسبُ من نصّ القرآن نفسِه، ونعرضُ المحسوبَ مادّةً بين يدَي القارئ؛ لا نُفسّرُ، ولا نُفتي، ولا نُقحِمُ رأيًا من عندنا. الغايةُ أداةٌ تُقرّبُ النظرَ في النصّ وتُعينُ على التدبّر والبحث، لا تفسيرٌ نُنشئه.\n\n**حدودٌ نلتزمها بصرامة.** منهجُنا أن نحسبَ من مصادرَ محدودةٍ معلومة، ونعرضَ ما حسبناه وحده:\n\n- نصُّ المصحف (مصحف المدينة، برسمِ عثمان طه)\n- معاني الكلمات من «المفردات» للراغب الأصفهانيّ و«مقاييس اللغة» لابن فارس\n- الوسمُ الصرفيّ لمُدوَّنة القرآن (QAC)\n- تضميناتُ نموذج Gemini للمعنى\n\nوما وراءها من علومٍ جليلةٍ نتركه لأهله: لا تفسير، ولا حديث، ولا أسباب نزول، ولا قراءات، ولا ناسخ ومنسوخ. وليس في هذا حكمٌ على تلك العلوم ولا استغناءٌ عنها — فالتفسيرُ والحديثُ وعلومُ القرآن أصلُ فهم الكتاب، ولها أهلُها الراسخون — وإنّما هو انضباطٌ في الأداة نَقصُرها على ما يُحسَبُ ويُتحقَّقُ منه. **فالمشروعُ رافدٌ، لا بديلٌ عن عالمٍ ولا عن كتاب.**",
    "en_body": "Mishkāt is an experiment in serving the Qur'an computationally: we build a *computed knowledge graph* over the muṣḥaf's text, aided by artificial intelligence within a disciplined frame, to bring out the Book's coherence and order — how its verses answer one another and its roots and meanings interlace into a single fabric.\n\nOur motto: **\"We compute, and we show.\"** We compute from the Qur'anic text itself and present the computed as material in the reader's hands; we do not interpret, do not issue rulings, and inject no opinion of our own. The aim is a tool that brings the reader closer to the text and aids reflection and study — not an interpretation we author.\n\n**Bounds we keep strictly.** Our method is to compute from a fixed, known set of sources and present only what we computed:\n\n- The Qur'anic text (Madina muṣḥaf, ʿUthmān Ṭāhā rasm)\n- Word meanings from al-Rāghib's *Mufradāt* and Ibn Fāris's *Maqāyīs al-Lugha*\n- The Quranic Arabic Corpus (QAC) morphology\n- Gemini meaning-embeddings\n\nThe greater sciences beyond these we leave to their scholars: no tafsīr, no ḥadīth, no occasions of revelation, no variant readings, no abrogation. This is no judgment on those sciences nor a doing-without them — tafsīr, ḥadīth and the Qur'anic sciences are the ground of understanding the Book, with their deeply-rooted scholars. It is a discipline of the tool: we keep it to what can be computed and verified. **The project is an aid, never a substitute for a scholar or a book.**"
  },
  {
    "id": "embeddings-vectors",
    "ar_heading": "كيف يقيسُ الحاسوبُ قُربَ المعنى؟ — التضميناتُ والمتّجهاتُ وجيبُ التمام",
    "en_heading": "How the machine measures closeness of meaning — embeddings, vectors, and cosine",
    "ar_body": "قلبُ المشروع حسابٌ لا رأي. لكنْ كيف «يقيسُ» جهازٌ معنى آية؟ الجوابُ في ثلاث خطواتٍ يقومُ عليها كلُّ ما نبنيه.\n\n**١. من المعنى إلى الأرقام — التضمين (embedding).** نُمرِّرُ كلَّ آيةٍ على نموذجٍ لغويٍّ ضخم (نموذج Gemini)، فيُحوّلُ معناها إلى سلسلةٍ من ٧٦٨ رقمًا تُسمَّى «المتَّجِه» (vector). فتصيرُ كلُّ آيةٍ نقطةً في «فضاءٍ للمعنى» ذي ٧٦٨ بُعدًا: النقاطُ المتقاربةُ فيه آياتٌ متقاربةُ المعنى، والمتباعدةُ متباعدتُه — بالمعنى لا باللفظ (فـ«أنفقوا» و«تصدَّقوا» متجاورتان وإن اختلفَ حرفُهما).\n\n**٢. قياسُ القرب — جيبُ التمام (cosine).** نقيسُ قُربَ آيتين بالزاويةِ بين متَّجهيهما: كلّما صغُرت الزاويةُ اشتدَّ تقاربُ المعنى — رقمٌ بين صفرٍ وواحد. هذا حسابٌ هندسيٌّ محضٌ، يُعادُ فيُعطي النتيجةَ نفسَها في كلِّ مرّة، لا يدخلُه رأيٌ ولا مِزاجٌ ولا تأويل.\n\n**٣. ماذا نبني على ذلك.** من هاتين اللبِنتين تنبثقُ أدواتٌ عِدّة:\n\n- **المركز (centroid):** متوسّطُ متَّجهاتِ مجموعةِ آياتٍ يُمثّلُ معناها الجامع. به رسَونا «مرساةَ التوحيد» (مركزَ آيات «لا إله إلا»)، وبه نتتبّعُ أيَّ معنًى عبر المصحف.\n- **التجميع (k-means):** نجمعُ الآياتِ في تسعينَ محورًا بحسبِ تجاورِها في الفضاء، ثمّ يُسمَّى كلُّ محورٍ بموضوعه.\n- **أقربُ الجيران:** نحفظُ لكلِّ آيةٍ أقربَ جيرانها معنًى عبر المصحف كلِّه، فعليها يقومُ «مثلها» والبحثُ الدلاليّ.\n\nوحدُّ الأمانة: النموذجُ يقيسُ قُربَ المعنى فحسب — لا يُفسّرُ، ولا يُفتي، ولا يُضيفُ من عندِه شيئًا.",
    "en_body": "The heart of the project is computation, not opinion. But how does a machine *measure* a verse's meaning? In three steps that everything here rests on.\n\n**1. From meaning to numbers — the embedding.** Each verse is passed through a large language model (Gemini), which turns its meaning into a list of 768 numbers — a *vector*. Every verse becomes a point in a 768-dimensional *meaning space*: nearby points are verses near in meaning, distant points distant in meaning — by meaning, not wording (so \"anfiqū\" and \"taṣaddaqū\" sit close though their letters differ).\n\n**2. Measuring closeness — cosine.** We gauge the closeness of two verses by the angle between their vectors: the smaller the angle, the closer the meaning — a number from 0 to 1. Pure geometry, giving the same result every run — no opinion, no mood, no interpretation enters it.\n\n**3. What we build on it.** From these two building blocks several instruments emerge:\n\n- **The centroid:** the average of a set of vectors represents their shared meaning. It anchors *tawḥīd* (the centre of the \"lā ilāha illā\" verses) and lets us trace any concept across the muṣḥaf.\n- **Clustering (k-means):** verses group into ninety themes by their proximity in the space, and each theme is then named by its subject.\n- **Nearest neighbours:** for every verse we keep its closest verses in meaning across the whole muṣḥaf, and on these «similar verses» and semantic search are built.\n\nThe bound of honesty: the model measures closeness of meaning only — it does not interpret, rule, or add anything of its own."
  },
  {
    "id": "jamiiyya-mizan",
    "ar_heading": "ميزانُ «الجامعيّة»: كيف نحسبُ أصالةَ الآية تمامًا",
    "en_heading": "The \"jāmiʿiyya\" measure: exactly how we compute a verse's foundational weight",
    "ar_body": "الميزانُ هو الإسهامُ الرائدُ في المشروع: مقياسٌ محسوبٌ **قابلٌ لإعادة الإنتاج تمامًا** يزنُ «جامعيّةَ» كلِّ آيةٍ من آيِ القرآن الستّةِ آلافٍ ومئتين وستٍّ وثلاثين — أهيَ أصلٌ جامعٌ تنضوي تحته المعاني، أم تفصيلٌ يتفرّعُ عنها؟ ويُحسَبُ من بيانات القرآن نفسِه، لا من رأيٍ ولا قائمةٍ مُعدّةٍ سلفًا.\n\n**العواملُ الستّة.** لكلِّ آيةٍ نحسبُ ستّةَ مقاييس، ثمّ نُحوّلُ كلًّا منها إلى مرتبةٍ مئويّةٍ بين الآيات (percentile)، ثمّ نجمعُها مجموعًا موزونًا:\n\n- **مرساةُ التوحيد (٢٤٪):** قُربُ الآيةِ من مركزِ متَّجهات آيات «لا إله إلا». بذرةٌ واحدةٌ معلَنةٌ صريحة — إذ الأصالةُ ليست سمةً في سطح النصّ تُلتقَطُ آليًّا، فأعلنّا مرساتَها.\n- **الاستقلالُ النحويّ (٢٢٪):** خِفّةُ اعتماد الآية على سياقها؛ نُنقِصُ من قيمتها بمقدار الأعلامِ وأسماءِ الإشارة والسرد الشرطيّ (من صرف QAC)، ونستثني اسمَ الله من الأعلام.\n- **عمومُ المفردات (٢٠٪):** متوسّطُ تواتر جذور الآية في القرآن كلِّه؛ فالكلماتُ العامّةُ الشائعةُ أجمعُ من الخاصّة.\n- **قوّةُ الإنشاء (١٢٪):** حضورُ الأمر والحصر والتوكيد (من صرف QAC) — أدواتِ التقرير والتأسيس.\n- **المعنى المركزيّ (١٢٪):** قُربُ الآية من مركز معاني القرآن كلِّه.\n- **السَّعةُ (١٠٪):** عددُ الجذور المتمايزة في الآية.\n\nومجموعُ هذه العوامل الموزون هو **«مؤشّرُ الجامعيّة»** لكلِّ آية.\n\n**المراتب.** يُرتَّبُ المؤشّرُ عبر المصحف كلِّه، فتنتظمُ الآياتُ في ثلاث مراتب:\n\n- **كلّيّة:** أعلى نحوِ ١٫٥٪، مُنقّاةٌ من التكرار (متى تقاربت كلّيّتان معنًى تقاربًا شديدًا رُدَّت الأدنى إلى ما تحتها — فلا رؤوسَ مكرّرةَ المعنى).\n- **جامعة:** آيةٌ تجمعُ تحتها تفصيلًا؛ وقاعدةُ الشجرة: الجامعةُ يجبُ أن تجمعَ آيةً فأكثر، وإلا فهي تفصيل.\n- **تفصيل:** ما تفرّعَ تحت جامعٍ أو كلّيّة.\n\nوالنتيجةُ الحاليّة: **٦٨ كلّيّةً · ٦١٧ جامعةً · ٥٥٥١ تفصيلًا**، شجرةً لا يتيمَ فيها ولا رأسَ بلا فرع.\n\n**إعادةُ الإنتاج.** كلُّ عاملٍ حسابٌ شفّاف، والخوارزميّةُ واحدةٌ للآيِ كلِّه — لا استثناءَ لآيةٍ بعينها، ولا تعديلَ يدويّ. تشغيلانِ متطابقانِ يُعطيانِ الشجرةَ نفسَها. ولوحةُ «لماذا هذه المرتبة؟» تعرضُ حسابَ العوامل الستّة لكلِّ آيةٍ عِيانًا.\n\n**دورُ الذكاء الاصطناعيّ هنا: التحقّقُ لا الصُّنع.** سِربٌ من النماذج يُقيّمُ عيّنةً مصنّفةً من الآيات تقييمًا أعمى (لا يرى مرتبتَها المحسوبة)، فنقيسُ توافقَ حكمِه مع الميزان. النتيجةُ: يمنحُ آياتِ التوحيد أعلى الدرجات، والسردَ أدناها — فيشهدُ للميزان. **الذكاءُ يشهدُ، ولا يصنع.**",
    "en_body": "The measure is the project's leading contribution: a **fully reproducible** computed score that weighs the *jāmiʿiyya* — the foundational, gathering weight — of each of the Qur'an's 6,236 verses. Is a verse a governing principle under which meanings gather, or a detail branching from them? It is computed from the Qur'an's own data — not from opinion, nor from any pre-made list.\n\n**The six factors.** For every verse we compute six measures, convert each into a percentile rank among the verses, then combine them in a weighted sum:\n\n- **Tawḥīd anchor (24%):** the verse's nearness to the centroid of the vectors of the \"lā ilāha illā\" verses. A single, openly declared seed — since foundation is not a surface property to be picked up automatically, we declared its anchor.\n- **Grammatical self-standing (22%):** how lightly the verse leans on its context; we discount it by its proper nouns, demonstratives, and narrative-conditional load (from QAC morphology), excluding the divine name from the proper nouns.\n- **Lexical generality (20%):** the mean corpus-frequency of the verse's roots; common, general words gather more than particular ones.\n- **Establishing force (12%):** presence of the imperative, restriction and emphasis (from QAC) — the instruments of assertion and foundation.\n- **Central meaning (12%):** the verse's nearness to the centroid of all the Qur'an's meanings.\n- **Breadth (10%):** the number of distinct roots in the verse.\n\nThe weighted sum of these factors is each verse's **jāmiʿiyya index**.\n\n**The tiers.** The index is ranked across the whole muṣḥaf, and verses settle into three tiers:\n\n- **Kulliyya:** the top ~1.5%, cleared of duplication (when two kulliyyāt are very close in meaning, the lesser folds down — no meaning-duplicate heads).\n- **Jāmiʿa:** a verse that gathers detail beneath it; the tree rule: a jāmiʿa must gather at least one child, else it is tafṣīl.\n- **Tafṣīl:** what branches under a jāmiʿa or kulliyya.\n\nThe current result: **68 kulliyyāt · 617 jawāmiʿ · 5,551 tafṣīl** — a tree with no orphan and no childless head.\n\n**Reproducibility.** Each factor is transparent computation, and the algorithm is one for all the verses — no exception for any single verse, no manual tweak. Two identical runs yield the same tree. A \"Why this rank?\" panel lays the six-factor arithmetic bare for every verse.\n\n**AI's role here: validation, not authorship.** A swarm of models blind-rates a stratified sample of verses (not seeing their computed tier), and we measure how far its judgment agrees with the measure. The result: it gives the tawḥīd verses the highest scores and narrative the lowest — bearing witness for the measure. **AI witnesses; it does not create.**"
  },
  {
    "id": "sections-on-mizan",
    "ar_heading": "جولةٌ في الأقسام: ما بُنِيَ على الميزان",
    "en_heading": "A tour of the sections: what is built on the measure",
    "ar_body": "من الميزان والمتّجهات تتفرّعُ الأقسامُ الآتية، كلٌّ يعملُ بطريقةٍ معلومة:\n\n**الكلّيّات (/kulliyat).** تصنيفُ كلّ آية: مرتبتُها، ومحورُها، ومؤشّرُها؛ ولوحةُ «لماذا هذه المرتبة؟» تُظهرُ حسابَ العوامل الستّة عِيانًا. تُعرَضُ بترتيب المصحف أو بترتيب الجامعيّة (الأصلُ أوّلًا).\n\n**خريطةُ المصحف (/shabaka).** كلُّ آيةٍ خليّةٌ ملوّنةٌ بمرتبتها المحسوبة — كلّيّةً أو جامعةً أو تفصيلًا — مصفوفةً بترتيب المصحف وسورِه؛ فتُرى في نظرةٍ واحدةٍ أين تقعُ الأصولُ الجامعةُ عبر القرآن كلِّه: هيكلُ الكتابِ كما يرسمُه الميزان.\n\n**الخيوطُ الموضوعيّة (/khayt).** تتبُّعُ أيِّ معنًى عبر المصحف: نبدأُ بتأصيلٍ لفظيٍّ دقيق (مواضعُ اللفظ ومواضعُ جذرِه) نواةً صُلبة، ثمّ نضيفُ هالةً دلاليّةً ضيّقةً من أقرب الآيات معنًى، مع بصمةِ حضورِ الخيط عبر السور الأربع عشرة بعد المئة. (وقد آثرنا التأصيلَ اللفظيَّ لأنّ القربَ الدلاليَّ وحده فضفاضٌ في الألفاظ الخاصّة.)\n\n**المواضيع (/mawdui).** موضوعاتُ القرآن كما تنشأُ حسابيًّا: تسعونَ محورًا تُجمَعُ إليها الآياتُ بتقاربِ المعنى فتُغطّي المصحفَ كلَّه، كلُّ آيةٍ في محورٍ واحد، وآياتُ كلِّ محورٍ مرتّبةٌ بالجامعيّة (الأصلُ أوّلًا). طبقةٌ موضوعيّةٌ واحدةٌ محسوبةٌ لا مُنتقاةٌ بالرأي.\n\n**البحث (/search).** بحثٌ دلاليٌّ (بالمعنى) ونصّيٌّ (باللفظ)، نتائجُه مرتّبةٌ بالجامعيّة فتَصعدُ الآياتُ الأصولُ إلى الصدارة.\n\n**نِبراس.** محادثةٌ بحثيّةٌ تسترجعُ من بياناتنا وتُؤلّفُ منها جوابًا، مؤصَّلةً على الآيات الأعلى جامعيّة؛ الذكاءُ يُؤلّفُ مادّةً محسوبةً ولا يتجاوزُها إلى تفسيرٍ من عنده.",
    "en_body": "From the measure and the vectors branch the following sections, each working in a known way:\n\n**Kulliyyāt (/kulliyat).** Every verse's classification: its tier, its theme, its index; and a \"Why this rank?\" panel that lays the six-factor arithmetic bare. Shown in muṣḥaf order or by jāmiʿiyya (the foundational first).\n\n**The mushaf map (/shabaka).** Every verse is a cell coloured by its computed tier — kulliyya, jāmiʿa, or tafṣīl — laid out in mushaf order by sūra; at a single glance you see where the foundational verses fall across the whole Qur'an: the skeleton of the book as the mīzān draws it.\n\n**Thematic threads (/khayt).** Tracing any concept across the muṣḥaf: we begin from a precise lexical grounding (the occurrences of the word and of its root) as a solid core, then add a tight semantic halo of the nearest verses, with a heat-strip of the thread's presence across the 114 sūras. (We favoured lexical grounding because semantic proximity alone is too loose for particular words.)\n\n**Topics (/mawdui).** The Qur'an's topics as computation yields them: ninety محاور that gather the verses by meaning-proximity to cover the whole muṣḥaf — each verse in exactly one — with each محور's verses ordered by jāmiʿiyya (the foundational first). One computed topic layer, not a picked index.\n\n**Search (/search).** Semantic (by meaning) and textual (by wording) search, its results ordered by jāmiʿiyya so the foundational verses rise to the top.\n\n**Nibrās.** A research chat that retrieves from our data and composes an answer from it, grounded on the highest-jāmiʿiyya verses; AI composes computed material and does not go past it into an interpretation of its own."
  },
  {
    "id": "other-tools",
    "ar_heading": "أدواتٌ أخرى في المشكاة",
    "en_heading": "Other instruments in Mishkāt",
    "ar_body": "وإلى جانب ما بُنِيَ على الميزان، أدواتٌ تخدمُ اللفظَ والمعنى:\n\n**فروق التنزيل.** نُحاذي آليًّا بين كلِّ آيتين متشابهتين لفظًا بخوارزمية محاذاة النصوص، فتظهرُ مواضعُ الاختلاف كلمةً كلمة: إبدالًا وتقديمًا وزيادةً وإيجازًا — نُبرِزُ الفرقَ، والقارئُ يتأمّلُه.\n\n**الفروق اللغويّة والمترادفات.** نُحوّلُ تعريفَ كلِّ جذرٍ في المعجمَين إلى متّجهِ معنًى، ثمّ نقيسُ القُربَ بينها: فأقربُها متّجهًا أقربُها معنًى (مترادفات)، وعناقيدُها المتبادلةُ حقولٌ دلاليّة.\n\n**الجذورُ والمعجمُ والصرف.** «المفردات» و«مقاييس اللغة» بين يديك، مع إحصاءٍ صرفيٍّ للقرآن كلِّه: نمرُّ على ١٣٠٬٠٣٠ مقطعًا في الوسم القرآنيّ (QAC) ونُحصي كلَّ سِمة — قسمَ الكلمة، ووزنَ الفعل وزمنَه، وحالتَه الإعرابيّة.\n\n**الأمثال.** أمثالُ القرآن مجموعةً منظومة.\n\n**أطلسُ الفواصل.** نظرةٌ في فواصل الآي وخواتيمِها.\n\nوكلُّ هذه البيانات محسوبةٌ قابلةٌ للفحص، تُنزَّلُ في ملفِّ Excel واحد.",
    "en_body": "Alongside what is built on the measure are instruments serving word and meaning:\n\n**Furūq al-tanzīl.** We align every pair of near-identical verses with a sequence-alignment algorithm, surfacing each difference word by word: substitution, reordering, addition and concision — we surface the difference; the reader contemplates it.\n\n**Lexical distinctions & synonyms.** We turn each root's lexicon definition into a meaning-vector, then measure closeness: nearest by vector is nearest by meaning (synonyms), and mutual clusters are semantic fields.\n\n**Roots, dictionary & morphology.** The *Mufradāt* and *Maqāyīs* at hand, with a morphology census of the whole Qur'an: we walk all 130,030 segments of the QAC morphology and tally every feature — word class, verb form and tense, grammatical case.\n\n**Parables.** The Qur'an's parables gathered and arranged.\n\n**Verse-ending atlas.** A look into the cadences and closings of the āyāt.\n\nAll of this data is computed and inspectable, downloadable in a single Excel file."
  },
  {
    "id": "closing",
    "ar_heading": "خاتمةٌ صادقة: بدايةُ الطريق",
    "en_heading": "An honest closing: the start of the road",
    "ar_body": "«مشكاة» مشروعٌ بحثيٌّ، لا مرجعٌ مُحكَم. حسبُنا أنّنا حسبنا من نصّ المصحف — بأدواتٍ معلومةٍ وحدودٍ صريحة — طبقةً من العلاقات والمعاني، وعرضناها في يُسرٍ ووضوح، إعانةً على النظر لا استبدالًا به.\n\nوما زلنا في بدايةِ الطريق في هذا الاتجاه: الميزانُ في مراجعة، وأوزانُه تُنقَّح، والأقسامُ تُثرى. والحسابُ — على انضباطه — يبقى مقاربةً بشريّةً قابلةً للخطأ والتحسين، لا وحيًا ولا حُكمًا.\n\nنُقدّمُ المحسوبَ مادّةً بين يدَي القارئ والباحث ليَزِنَه بعلمه، وليردَّه إلى أهل التفسير والحديث وعلوم القرآن حيث يجبُ الردّ. **نحسبُ ونعرض؛ والفهمُ والحكمُ لأهله.**",
    "en_body": "Mishkāt is a research project, not a settled reference. Our claim is only that we have computed — from the muṣḥaf's text, with known tools and stated bounds — a layer of relations and meanings, and presented it plainly, to aid looking rather than to replace it.\n\nAnd we are still at the start of the road in this direction: the measure is under review, its weights are being refined, the sections are being enriched. Computation, for all its discipline, remains a human approach open to error and improvement — not revelation, and not a verdict.\n\nWe offer the computed as material in the hands of the reader and the researcher, to weigh by their knowledge and to return to the people of tafsīr, ḥadīth and the Qur'anic sciences where return is due. **We compute, and we show; understanding and judgment belong to their people.**"
  }
];
